version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./t2m-frontend
      dockerfile: Dockerfile
    command: node server.js

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  backend:
    container_name: backend
    build:
      context: ./t2m-backend
      dockerfile: Dockerfile
    command: npm run start
    expose:
      - 8000
