export const ADMIN_ROLE = "T2M ADMIN";
export const USER_ROLE = "T2M USER";
export const CTV_ROLE = "T2M CTV";

export const INIT_PERMISSIONS = [
    {
        "_id": "",
        "name": "Fetch all orders with paginate",
        "apiPath": "/api/v1/orders",
        "method": "GET",
        "module": "ORDERS",
    },
    {
        "_id": "",
        "name": "Fetch all orders",
        "apiPath": "/api/v1/orders/all",
        "method": "GET",
        "module": "ORDERS",
    },
    {
        "_id": "",
        "name": "Find a discount code by id",
        "apiPath": "/api/v1/discountcodes/:id",
        "method": "GET",
        "module": "DISCOUNTCODES",
    },
    {
        "_id": "",
        "name": "Update a discount code by id",
        "apiPath": "/api/v1/discountcodes/:id",
        "method": "PUT",
        "module": "DISCOUNTCODES",
    },
    {
        "_id": "",
        "name": "Delete a discount code by id",
        "apiPath": "/api/v1/discountcodes/:id",
        "method": "DELETE",
        "module": "DISCOUNTCODES",
    },
    {
        "_id": "",
        "name": "Find a discount code by id",
        "apiPath": "/api/v1/discountcodes/:id",
        "method": "GET",
        "module": "DISCOUNTCODES",
    },
    {
        "_id": "",
        "name": "Fetch all discount code with paginate",
        "apiPath": "/api/v1/discountcodes",
        "method": "GET",
        "module": "DISCOUNTCODES",
    },
    {
        "_id": "",
        "name": "Create a discount code",
        "apiPath": "/api/v1/discountcodes/:id",
        "method": "PATCH",
        "module": "DISCOUNTCODES",
    },
    {
        "_id": "",
        "name": "Create a discount code",
        "apiPath": "/api/v1/discountcodes",
        "method": "POST",
        "module": "DISCOUNTCODES",
    },
    {
        "_id": "",
        "name": "Create a discount code",
        "apiPath": "/api/v1/discountcodes/find-by-code",
        "method": "POST",
        "module": "DISCOUNTCODES",
    },

    {
        "_id": "",
        "name": "Manage CTV",
        "apiPath": "/api/v1/users/manage-ctv",
        "method": "POST",
        "module": "USERS",
    },
    {
        "_id": "",
        "name": "Fetch all dependent users with paginate",
        "apiPath": "/api/v1/users/dependent",
        "method": "GET",
        "module": "USERS",
    },
    {
        "_id": "",
        "name": "Find user by email",
        "apiPath": "/api/v1/users/find-by-email",
        "method": "POST",
        "module": "USERS",
    },


    {
        "_id": "",
        "name": "Delete a License by ID",
        "apiPath": "/api/v1/licenses/:id",
        "method": "DELETE",
        "module": "LICENSES",
    },
    {
        "_id": "",
        "name": "Update a License by ID",
        "apiPath": "/api/v1/licenses/:id",
        "method": "PUT",
        "module": "LICENSES",
    },
    {
        "_id": "",
        "name": "Change Activation a License by ID",
        "apiPath": "/api/v1/licenses/:id",
        "method": "PATCH",
        "module": "LICENSES",
    },
    {
        "_id": "",
        "name": "Fetch a License by ID",
        "apiPath": "/api/v1/licenses/:id",
        "method": "GET",
        "module": "LICENSES",
    },
    {
        "_id": "",
        "name": "Fetch all License with paginate",
        "apiPath": "/api/v1/licenses",
        "method": "GET",
        "module": "LICENSES",
    },
    {
        "_id": "",
        "name": "Create a License",
        "apiPath": "/api/v1/licenses",
        "method": "POST",
        "module": "LICENSES",
    },
    {
        "_id": "",
        "name": "Extend a License",
        "apiPath": "/api/v1/licenses/extend",
        "method": "POST",
        "module": "LICENSES",
    },
    {
        "_id": "",
        "name": "Undo Extend a License",
        "apiPath": "/api/v1/licenses/undo-extend",
        "method": "POST",
        "module": "LICENSES",
    },
    {
        "_id": "",
        "name": "Delete a Product by ID",
        "apiPath": "/api/v1/products/:id",
        "method": "DELETE",
        "module": "PRODUCTS",
    },
    {
        "_id": "",
        "name": "Change Activation a Product by ID",
        "apiPath": "/api/v1/products/:id",
        "method": "PATCH",
        "module": "PRODUCTS",
    },
    {
        "_id": "",
        "name": "Update a Product by ID",
        "apiPath": "/api/v1/products/:id",
        "method": "PUT",
        "module": "PRODUCTS",
    },
    {
        "_id": "",
        "name": "Fetch a Product by ID",
        "apiPath": "/api/v1/products/:id",
        "method": "GET",
        "module": "PRODUCTS",
    },
    {
        "_id": "",
        "name": "Fetch all Product with paginate",
        "apiPath": "/api/v1/products",
        "method": "GET",
        "module": "PRODUCTS",
    },
    {
        "_id": "",
        "name": "Create a Product",
        "apiPath": "/api/v1/products",
        "method": "POST",
        "module": "PRODUCTS",
    },
    {
        "_id": "",
        "name": "Find a Product by name",
        "apiPath": "/api/v1/products/find-by-product",
        "method": "POST",
        "module": "PRODUCTS",
    },
    {
        "_id": "",
        "name": "Delete a Role by ID",
        "apiPath": "/api/v1/roles/:id",
        "method": "DELETE",
        "module": "ROLES",
    },
    {
        "_id": "",
        "name": "Update a Role by ID",
        "apiPath": "/api/v1/roles/:id",
        "method": "PATCH",
        "module": "ROLES",
    },
    {
        "_id": "",
        "name": "Fetch a Role by ID",
        "apiPath": "/api/v1/roles/:id",
        "method": "GET",
        "module": "ROLES",
    },
    {
        "_id": "",
        "name": "Fetch all Role with paginate",
        "apiPath": "/api/v1/roles",
        "method": "GET",
        "module": "ROLES",
    },
    {
        "_id": "",
        "name": "Create a Role",
        "apiPath": "/api/v1/roles",
        "method": "POST",
        "module": "ROLES",
    },
    {
        "_id": "",
        "name": "ADMIN Change Password",
        "apiPath": "/api/v1/users/admin-change-password",
        "method": "POST",
        "module": "USERS",
    },
    {
        "_id": "",
        "name": "Change Password",
        "apiPath": "/api/v1/users/change-password",
        "method": "POST",
        "module": "USERS",
    },
    {
        "_id": "",
        "name": "Delete a User by ID",
        "apiPath": "/api/v1/users/:id",
        "method": "DELETE",
        "module": "USERS",
    },
    {
        "_id": "",
        "name": "Update a User by ID",
        "apiPath": "/api/v1/users/:id",
        "method": "PATCH",
        "module": "USERS",
    },
    {
        "_id": "",
        "name": "Fetch a User by ID",
        "apiPath": "/api/v1/users/:id",
        "method": "GET",
        "module": "USERS",
    },
    {
        "_id": "",
        "name": "Get list uesr email",
        "apiPath": "/api/v1/users/email-list",
        "method": "GET",
        "module": "USERS",
    },
    {
        "_id": "",
        "name": "Fetch all User with paginate",
        "apiPath": "/api/v1/users",
        "method": "GET",
        "module": "USERS",
    },
    {
        "_id": "",
        "name": "Fetch all Users",
        "apiPath": "/api/v1/users/all",
        "method": "GET",
        "module": "USERS",
    },
    {
        "_id": "",
        "name": "Create a User",
        "apiPath": "/api/v1/users",
        "method": "POST",
        "module": "USERS",
    },
    {
        "_id": "",
        "name": "Delete a Permission by ID",
        "apiPath": "/api/v1/permissions/:id",
        "method": "DELETE",
        "module": "PERMISSIONS",
    },
    {
        "_id": "",
        "name": "Update a Permission by ID",
        "apiPath": "/api/v1/permissions/:id",
        "method": "PATCH",
        "module": "PERMISSIONS",
    },
    {
        "_id": "",
        "name": "Fetch a Permission by ID",
        "apiPath": "/api/v1/permissions/:id",
        "method": "GET",
        "module": "PERMISSIONS",
    },
    {
        "_id": "",
        "name": "Fetch all Permission with paginate",
        "apiPath": "/api/v1/permissions",
        "method": "GET",
        "module": "PERMISSIONS",
    },
    {
        "_id": "",
        "name": "Create a Permission",
        "apiPath": "/api/v1/permissions",
        "method": "POST",
        "module": "PERMISSIONS",
    }
]